[package]
name = "bridge_client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features= ["derive"] }
bincode = "1.3"
ctrlc = "3.4"

bridge_core = { path = "../bridge_core" }
